name: Move issues between columns on close/reopen

on:
  issues:
    types: [closed, reopened]

jobs:
  move_card:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Move card based on issue state
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const todoColumnId = "f75ad846";
            const doneColumnId = "98236657";

            // We'll scan all columns just in case
            const projectColumns = [todoColumnId, doneColumnId];

            let allCards = [];
            for (const columnId of projectColumns) {
              const cards = await github.rest.projects.listCards({
                column_id: columnId,
                per_page: 100
              });
              allCards = allCards.concat(cards.data);
            }

            const issueCard = allCards.find(
              c => c.content_url && c.content_url.endsWith(`/issues/${context.issue.number}`)
            );

            if (!issueCard) {
              console.log(" No project card found for this issue.");
              return;
            }

            const targetColumn = context.payload.issue.state === "closed" ? doneColumnId : todoColumnId;

            if (issueCard.column_id === targetColumn) {
              console.log(" Card already in correct column.");
              return;
            }

            await github.rest.projects.moveCard({
              card_id: issueCard.id,
              position: "top",
              column_id: targetColumn
            });

            console.log(`Moved issue #${context.issue.number} to column ${targetColumn}.`);
